### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by renjiawei-cr7** [ChenHongruixuan/ObjFormer#1]
可以更新一下代码吗，仅供学习使用，谢谢。

**Comment by ChenHongruixuan** [comment]
Thank you for your inquiry! The dataset and code in this work will be open-sourced upon acceptance of this work.

**Comment by ChenHongruixuan** [comment]
Hi @renjiawei-cr7 ,

The code for training and evalution has been uploaded. Sorry for taking  so long. 

Best,
