### ISSUE TITLE
Issue about semantic change labels

### ISSUE THREAD

**Issue by ShuGuoJ** [ChenHongruixuan/ObjFormer#3]
What do numbers in semantic change labels mean? Does 0 mean change from "background" to "background" and 1 mean change from "background" to "Bareland"?

**Comment by ChenHongruixuan** [comment]
Hi @ShuGuoJ ,

We have uploaded the training code for semantic change detection and dataset. You can check the information for "from-to" transition matrix in the script [train_benchmark_scd.py].

Best,
